version: '3.7'
services:
  aero_back:
    restart: always
    image: openjdk:17-alpine
    volumes:
      - ./jars:/app
    working_dir: /app
    env_file:
      - .env
    command: java -jar hr-platform-1.0.0.jar
    ports:
      - "8080:8080"

  front_container:
    restart: always
    image: nginx:latest
    volumes:
      - ./web/:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    ports:
      - "80:80"